# Generated by Django 3.0.7 on 2022-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoDashboard', '0003_add_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcolumn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='time_estimate_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
